# Generated by Django 6.0.2 on 2026-02-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Main project description')),
                ('featured_image', models.ImageField(blank=True, help_text='Main project image', null=True, upload_to='projects/')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom project attributes (technologies, links, galleries, etc.)')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this project is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
