# Generated by Django 6.0.2 on 2026-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for browser tab (recommended: 32x32px or 64x64px PNG/ICO)', null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image for navbar (recommended: 200x50px PNG with transparent background)', null=True, upload_to='branding/'),
        ),
    ]
