# Generated by Django 6.0.2 on 2026-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Job description and responsibilities. Supports Markdown formatting for easy bullet points and paragraphs.'),
        ),
    ]
