# Generated by Django 6.0.2 on 2026-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='association',
            field=models.CharField(blank=True, help_text='Client, Company, or Organization associated with this project', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text="Your role in the project (e.g., 'Lead Developer', 'Researcher')", max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='time_frame',
            field=models.CharField(blank=True, help_text="Duration or period (e.g., 'Jan 2023 - Present', '3 months')", max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Main project description. Supports Markdown formatting.'),
        ),
    ]
