# Generated by Django 6.0.2 on 2026-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_association_project_role_project_time_frame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='University/College/School name', max_length=200)),
                ('degree', models.CharField(help_text='Degree/Certificate name', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location (optional)', max_length=200)),
                ('start_date', models.DateField(help_text='Start date')),
                ('end_date', models.DateField(blank=True, help_text='End date (leave blank if current)', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying here')),
                ('description', models.TextField(blank=True, help_text='Optional description. Supports Markdown.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
